// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: miaosha.proto
#ifndef GRPC_miaosha_2eproto__INCLUDED
#define GRPC_miaosha_2eproto__INCLUDED

#include "miaosha.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace miaosha {

class MiaoshaService final {
 public:
  static constexpr char const* service_full_name() {
    return "miaosha.MiaoshaService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status miaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::miaosha::MiaoshaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>> Asyncmiaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>>(AsyncmiaoshaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>> PrepareAsyncmiaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>>(PrepareAsyncmiaoshaRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void miaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void miaosha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::miaosha::MiaoshaResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>* AsyncmiaoshaRaw(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::miaosha::MiaoshaResponse>* PrepareAsyncmiaoshaRaw(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status miaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::miaosha::MiaoshaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>> Asyncmiaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>>(AsyncmiaoshaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>> PrepareAsyncmiaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>>(PrepareAsyncmiaoshaRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void miaosha(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response, std::function<void(::grpc::Status)>) override;
      void miaosha(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::miaosha::MiaoshaResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>* AsyncmiaoshaRaw(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::miaosha::MiaoshaResponse>* PrepareAsyncmiaoshaRaw(::grpc::ClientContext* context, const ::miaosha::MiaoshaRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_miaosha_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_miaosha() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmiaosha(::grpc::ServerContext* context, ::miaosha::MiaoshaRequest* request, ::grpc::ServerAsyncResponseWriter< ::miaosha::MiaoshaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_miaosha<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_miaosha() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::miaosha::MiaoshaRequest, ::miaosha::MiaoshaResponse>(
          [this](::grpc::ServerContext* context,
                 const ::miaosha::MiaoshaRequest* request,
                 ::miaosha::MiaoshaResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->miaosha(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_miaosha<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_miaosha() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_miaosha() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmiaosha(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_miaosha() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->miaosha(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void miaosha(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_miaosha : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_miaosha() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::miaosha::MiaoshaRequest, ::miaosha::MiaoshaResponse>(std::bind(&WithStreamedUnaryMethod_miaosha<BaseClass>::Streamedmiaosha, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_miaosha() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status miaosha(::grpc::ServerContext* context, const ::miaosha::MiaoshaRequest* request, ::miaosha::MiaoshaResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedmiaosha(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::miaosha::MiaoshaRequest,::miaosha::MiaoshaResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_miaosha<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_miaosha<Service > StreamedService;
};

}  // namespace miaosha


#endif  // GRPC_miaosha_2eproto__INCLUDED
